from StreamShield.input.input_handler import process_input
from StreamShield.input.audio_extractor import extract_audio
from StreamShield.input.frame_extractor import frame_generator
from StreamShield.input.webcam_stream import start_webcam_stream